---

- name: install fastd
  package:
    name: ["fastd"]
    state: present

- name: Add fastd group
  group: name={{ fastd_user_name }} system=yes state=present

- name: Add fastd user
  user: createhome=no system=yes shell={{ fastd_user_shell }} name={{ fastd_user_name }}

- name: create fastd config directory
  file: path=/etc/fastd state=directory owner={{ fastd_user_name }} group={{ fastd_user_name }} mode=0700

- name: create fastd instance config directories
  file: path=/etc/fastd/{{ item.name }} state=directory owner={{ fastd_user_name }} group={{ fastd_user_name }} mode=0700
  with_items:
    - "{{ fastd_instances }}"

- name: create fastd configuration
  template: src=templates/fastd.conf.j2 dest=/etc/fastd/{{ item.name }}/fastd.conf owner={{ fastd_user_name }} group={{ fastd_user_name }} mode=0600
  with_items:
    - "{{ fastd_instances }}"
  notify: fastd restart

- name: create fastd secrets
  template: src=templates/secret.conf.j2 dest=/etc/fastd/{{ item.name }}/secret.conf owner={{ fastd_user_name }} group={{ fastd_user_name }} mode=0600
  no_log: true
  with_items:
    - "{{ fastd_instances_secret }}"
  notify: fastd restart

- name: create fastd peer include directories
  when: item.peer_dir is defined
  file: dest={{ item.peer_dir }} state=directory owner={{ fastd_user_name }} group={{ fastd_user_name }} mode=0700
  with_items:
    - "{{ fastd_instances }}"

- name: Create fastd peer configs
  when: item.0.peer_dir is defined
  template: src=templates/peer.config.j2 dest="{{ item.0.peer_dir }}/{{ item.1.name }}" owner={{ fastd_user_name }} group={{ fastd_user_name }} mode=0600
  with_subelements:
    - "{{ fastd_instances | selectattr('peers', 'defined') | list }}"
    - peers

- name: create fastd firewall rules
  template: src=templates/1010-fastd.conf.j2 dest=/etc/ferm/ferm.d/1010-fastd.conf owner=root group=root
  notify:
    - ferm restart

- name: create fastd service
  template: src=templates/fastd@.service.j2 dest=/usr/lib/systemd/system/fastd@.service.j2 owner=root group=root

- name: fastd needs to autostart
  service: name=fastd@{{ item.name }}.service enabled=yes state=restarted
  with_items:
    - "{{ fastd_instances }}"
